### ISSUE TITLE
Add custom query parameters to file

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/plinko-probability#39]
PhET has begun to document custom query parameters in a separate file so that they are documented and easy to find.  Would you mind doing this for the 'lowerBallMaximum' parameter?  Please see AreaBuilderQueryParameters for an example.

**Comment by veillette** [comment]
I'm assigning this one to you @Denz1994 . Our query parameter was somewhat of a hack (although it was useful for the QA team). A better query parameter might be ?launchedBalls=###, which would prepopulate the histogram with that many balls. That could be useful on the second screen.

**Comment by Denz1994** [comment]
The "lowerBallMaximum" parameter has been replaced by "ballsOnScreen" for more flexibility. Now users can enter "?ballsOnScreen=450" and the lab tab, once opened, will be initialized as if 450 balls have fallen. This includes updating the histogram along with the statistics associated with 450 randomly dropped balls (the histogram differs every time, as it should). 

This may be useful for instructors as well, if they wish to start the simulation with a specific number of balls, rather than waiting for a specific number of balls to drop.

Additionally, the query parameter file contains these metrics and has been created as suggested. Assigning to @jessegreenberg for review and any further input.

**Comment by jessegreenberg** [comment]
@Denz1994 PlinkoProbabilityQueryParameters looks great.  ```?launchedBalls=###``` is a very helpful addition!  Closing.
