### ISSUE TITLE
stringTest=xss doesn't load

### ISSUE THREAD

**Issue by BryceAG** [phetsims/plinko-probability#88]
Test device:
Bates

Operating System:
Windows 7

Browser:
Chrome, Firefox, and IE11

Problem description:
When testing stringTest=xss, the page doesn't load, and will not allow you to go back in history to a previous working string test or base rc test. if there is another tab with the rc test open, that tab will also stop responding.

Steps to reproduce:
add ?stringTest=xss to the URL

Severity:

Screenshots:
![image](https://cloud.githubusercontent.com/assets/15327201/18602942/9aa0518a-7c2a-11e6-9ab4-65eaf1691241.png)
here it should be fully loaded as the refresh button shows and there is no loading circle in the tab, but it isn't

Troubleshooting information (do not edit):
Name: ‪Plinko Probability‬
URL: http://www.colorado.edu/physics/phet/dev/html/plinko-probability/1.0.0-rc.1/plinko-probability_en.html
Version: 1.0.0-rc.1 2016-09-16 19:30:26 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.101 Safari/537.36
Language: en-US
Window: 1366x662
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 10 uniform: 253
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 4096x4096
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"HEAD"},"axon":{"sha":"e0192608","branch":"HEAD"},"babel":{"sha":"c041de05","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"HEAD"},"chipper":{"sha":"07058555","branch":"HEAD"},"dot":{"sha":"39436598","branch":"HEAD"},"joist":{"sha":"b513b5ee","branch":"HEAD"},"kite":{"sha":"73302899","branch":"HEAD"},"phet-core":{"sha":"c48bf320","branch":"HEAD"},"phetcommon":{"sha":"83ea84c8","branch":"HEAD"},"plinko-probability":{"sha":"3a105d26","branch":"HEAD"},"query-string-machine":{"sha":"05231e54","branch":"HEAD"},"scenery":{"sha":"e78ee413","branch":"HEAD"},"scenery-phet":{"sha":"f0fc9ae8","branch":"HEAD"},"sherpa":{"sha":"bcc28cd6","branch":"HEAD"},"sun":{"sha":"f2bd9d60","branch":"HEAD"},"tandem":{"sha":"d369b847","branch":"HEAD"},"vibe":{"sha":"b422db9c","branch":"HEAD"}}

related to phetsims/tasks#702

**Comment by phet-steele** [comment]
Also seen on Mac OSX 10.11.6 Chrome. The dev tools are not revealing anything helpful (to my limited knowledge at least).

**Comment by pixelzoom** [comment]
Reproduced.  My browser (Chrome on Mac) also becomes unresponsive and must be killed and restarted.

Other sims seem to have a similar problem, e.g.:
https://github.com/phetsims/atomic-interactions/issues/58

**Comment by pixelzoom** [comment]
In a Skype discussion with @jbphet and @jonathanolson, it was pointed out that `stringTest=xss` is considered successful if the sim does not redirect.  So this sim is technically passing the test, and I'm closing this issue as "won't fix".

If was also noted that the string substituted for `stringTest=xss` contains HTML markup, and that can cause problems depending on what scenery/scenery-phet/sun components are used by a sim.  For example, if a sim uses `SubSupText`, then it will fail due to an unexpected HTML tag. Do we want to chase down these problems? Should the sim still start and be functional?  Those general issues will be sorted out in https://github.com/phetsims/special-ops/issues/33.
